# py11: NumPy 数组、dtype 与形状

本 notebook 对应 NumPy 入门中的数组创建、数据类型、结构化数组、数组形状和常用属性。


In [1]:
import numpy as np


## 1. 使用 np.array 创建数组


In [2]:
# numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
a = np.array([1, 2, 3])
print(a)

a = np.array([[1, 2], [3, 4]])
print(a)

a = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a)

a = np.array([1, 2, 3], dtype=complex)
print(a)


[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


## 2. dtype 的基础写法


In [3]:
# 使用标量类型
dt = np.dtype(np.int32)
print(dt)

# int8、int16、int32、int64 可以使用字符串 'i1'、'i2'、'i4'、'i8' 代替
dt = np.dtype('i4')
print(dt)

# 字节顺序标注
dt = np.dtype('<i4')
print(dt)


int32
int32
int32


## 3. 单字段结构化数组


In [4]:
# 首先创建结构化数据类型
dt = np.dtype([('age', np.int8)])
print(dt)

# 将数据类型应用于 ndarray 对象
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a)

# 类型字段名可以用于存取实际的 age 列
print(a['age'])


[('age', 'i1')]
[(10,) (20,) (30,)]
[10 20 30]


## 4. 多字段结构化数组


In [5]:
dt = np.dtype([
    ('name', 'U10'),
    ('age', np.int8),
    ('height', np.float32)
])

a = np.array([
    ('Tom', 18, 175.5),
    ('Jack', 20, 180.0),
    ('Lucy', 19, 165.2)
], dtype=dt)

print(a)
print(a['name'])
print(a['age'])
print(a['height'])


[('Tom', 18, 175.5) ('Jack', 20, 180. ) ('Lucy', 19, 165.2)]
['Tom' 'Jack' 'Lucy']
[18 20 19]
[175.5 180.  165.2]


## 5. 字节字符串字段


In [6]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
# S20 表示字符串长度为 20，i1 表示 8 位整数，f4 表示 32 位浮点数
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype=student)
print(a)


[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


## 6. 维度、形状与 reshape


In [7]:
a = np.arange(24)
print(a.ndim)  # a 现在只有一个维度

b = a.reshape(2, 4, 3)  # b 现在拥有三个维度
print(b.ndim)

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

a.shape = (3, 2)
print(a)

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(b)


1
3
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


## 7. itemsize 与 flags


In [8]:
# 数组的 dtype 为 int8，一个元素占 1 个字节
x = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(x.itemsize)

# 数组的 dtype 为 float64，一个元素占 8 个字节
y = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(y.itemsize)

x = np.array([1, 2, 3, 4, 5])
print(x.flags)


1
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

