# py12: NumPy 常用数组创建函数

本 notebook 汇总 empty、zeros、ones、asarray、frombuffer、fromiter、arange、linspace 和 logspace 的常见用法。


In [1]:
import numpy as np


## 1. empty、zeros 与 ones


In [2]:
# numpy.empty(shape, dtype=float, order='C')
x = np.empty([3, 2], dtype=int)
print(x)

# numpy.zeros(shape, dtype=float, order='C')
x = np.zeros(5)  # 默认为浮点数
print(x)

y = np.zeros((5,), dtype=int)  # 设置类型为整数
print(y)

z = np.zeros((2, 2), dtype=[('x', 'i4'), ('y', 'i4')])  # 自定义类型
print(z)

# numpy.ones(shape, dtype=float, order='C')
x = np.ones(5)  # 默认为浮点数
print(x)

x = np.ones([2, 2], dtype=int)
print(x)


[[1632595968        388]
 [         0          0]
 [    131074  268502530]]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


## 2. zeros_like 与 ones_like


In [3]:
# numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

# numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)
ones_arr = np.ones_like(arr)
print(ones_arr)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## 3. asarray


In [4]:
# numpy.asarray(a, dtype=None, order=None)
x = [1, 2, 3]
a = np.asarray(x)
print(a)

x = (1, 2, 3)
a = np.asarray(x)
print(a)

x = [(1, 2, 3), (4, 5)]
a = np.asarray(x, dtype=object)
print(a)

x = [1, 2, 3]
a = np.asarray(x, dtype=float)
print(a)


[1 2 3]
[1 2 3]
[(1, 2, 3) (4, 5)]
[1. 2. 3.]


## 4. frombuffer 与 fromiter


In [5]:
s = b'Hello World'
a = np.frombuffer(s, dtype='S1')
print(a)

# 使用 range 对象创建迭代器，再从迭代器创建 ndarray
values = range(5)
it = iter(values)
x = np.fromiter(it, dtype=float)
print(x)


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
[0. 1. 2. 3. 4.]


## 5. arange


In [6]:
# numpy.arange(start, stop, step, dtype)
x = np.arange(5)
print(x)

x = np.arange(5, dtype=float)
print(x)

x = np.arange(10, 20, 2)
print(x)


[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]


## 6. linspace


In [7]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
a = np.linspace(1, 10, 10)
print(a)

a = np.linspace(1, 1, 10)
print(a)

a = np.linspace(10, 20, 5, endpoint=False)
print(a)

a = np.linspace(1, 10, 10, retstep=True)
print(a)

# 拓展例子
b = np.linspace(1, 10, 10).reshape([10, 1])
print(b)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10. 12. 14. 16. 18.]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


## 7. logspace


In [8]:
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
# 默认底数是 10
a = np.logspace(1.0, 2.0, num=10)
print(a)

a = np.logspace(0, 9, 10, base=2)
print(a)


[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
