# py13: NumPy 切片和索引

本 notebook 演示 ndarray 的单元素索引、切片、整数数组索引、布尔索引和花式索引。

In [9]:
import numpy as np

## 1. 一维数组索引与切片

In [10]:
a = np.arange(10)
print('a =', a)

# 单元素索引（从 0 开始）
print('a[0] =', a[0])
print('a[-1] =', a[-1])

# 切片：a[start:stop:step]，左闭右开
print('a[2:5] =', a[2:5])
print('a[:4] =', a[:4])
print('a[6:] =', a[6:])
print('a[::2] =', a[::2])     # 每隔一个取
print('a[::-1] =', a[::-1])   # 反转

# 切片是视图（view），修改会影响原数组
b = a[1:4]
b[0] = 99
print('修改切片后 a =', a)   # a[1] 也变成了 99

a = [0 1 2 3 4 5 6 7 8 9]
a[0] = 0
a[-1] = 9
a[2:5] = [2 3 4]
a[:4] = [0 1 2 3]
a[6:] = [6 7 8 9]
a[::2] = [0 2 4 6 8]
a[::-1] = [9 8 7 6 5 4 3 2 1 0]
修改切片后 a = [ 0 99  2  3  4  5  6  7  8  9]


## 2. 二维数组索引与切片

In [11]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print('a =')
print(a)

# 行索引
print('a[0] =', a[0])        # 第 0 行
print('a[-1] =', a[-1])      # 最后一行

# 行列索引 a[row, col]
print('a[1, 2] =', a[1, 2])  # 第 1 行第 2 列 → 6
print('a[2, 0] =', a[2, 0])  # 第 2 行第 0 列 → 7

# 行切片
print('a[0:2, :] =')
print(a[0:2, :])             # 取前两行

# 列切片
print('a[:, 1] =', a[:, 1])  # 取第 1 列
print('a[:, 0:2] =')
print(a[:, 0:2])             # 取前两列

# 行列同时切片
print('a[0:2, 1:3] =')
print(a[0:2, 1:3])           # 右上 2×2 子矩阵

a =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
a[0] = [1 2 3]
a[-1] = [7 8 9]
a[1, 2] = 6
a[2, 0] = 7
a[0:2, :] =
[[1 2 3]
 [4 5 6]]
a[:, 1] = [2 5 8]
a[:, 0:2] =
[[1 2]
 [4 5]
 [7 8]]
a[0:2, 1:3] =
[[2 3]
 [5 6]]


## 3. 花式索引（整数数组索引）

In [12]:
# ---- 一维数组花式索引 ----
x = np.arange(9)
print('x =', x)

# 读取下标对应的元素
x2 = x[[0, 6]]  # 使用花式索引
print('x[[0, 6]] =', x2)

print('x2[0] =', x2[0])  # 0
print('x2[1] =', x2[1])  # 6

x = [0 1 2 3 4 5 6 7 8]
x[[0, 6]] = [0 6]
x2[0] = 0
x2[1] = 6


In [13]:
# ---- 二维数组花式索引 ----
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print('a =')
print(a)

# 用整数数组指定要取的行（返回对应下标的行）
rows = np.array([0, 2, 3])
print('a[rows] =')
print(a[rows])  # 取第 0、2、3 行

a =
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
a[rows] =
[[1 2]
 [5 6]
 [7 8]]


In [14]:
# ---- 同时指定行和列的索引数组（逐元素配对） ----
cols = np.array([1, 0, 1])
print('a[rows, cols] =', a[rows, cols])  # a[0,1], a[2,0], a[3,1] → [2 5 7]

a[rows, cols] = [2 5 8]


In [15]:
# ---- np.ix_ 生成开放网格索引（笛卡尔积） ----
print('a[np.ix_([0,2], [0,1])] =')
print(a[np.ix_([0, 2], [0, 1])])  # 第 0、2 行 × 第 0、1 列的交叉部分

a[np.ix_([0,2], [0,1])] =
[[1 2]
 [5 6]]


In [16]:
# ---- 花式索引是复制，不是视图 ----
x = np.array([10, 20, 30, 40, 50])
idx = x[[0, 2]]       # 花式索引，数据被复制到新数组
idx[0] = 999
print('修改花式索引后 x =', x)   # x 不受影响 → [10 20 30 40 50]
print('idx =', idx)              # [999  30]

修改花式索引后 x = [10 20 30 40 50]
idx = [999  30]


## 4. 布尔索引

In [17]:
a = np.array([10, 20, 30, 40, 50])
print('a =', a)

# 布尔数组索引：返回 True 对应的元素
mask = np.array([True, False, True, False, True])
print('a[mask] =', a[mask])   # [10, 30, 50]

# 用条件表达式生成布尔掩码
print('a > 25 =', a > 25)     # [False False True True True]
print('a[a > 25] =', a[a > 25])  # [30 40 50]

# 组合条件用 &（与）、|（或），注意加括号
print('a[(a > 15) & (a < 45)] =', a[(a > 15) & (a < 45)])  # [20 30 40]

# 二维数组布尔索引
b = np.array([[1, 2], [3, 4], [5, 6]])
mask2 = np.array([[True, False],
                  [False, True],
                  [True, False]])
print('b[mask2] =', b[mask2])  # 一维结果：[1 4 5]

a = [10 20 30 40 50]
a[mask] = [10 30 50]
a > 25 = [False False  True  True  True]
a[a > 25] = [30 40 50]
a[(a > 15) & (a < 45)] = [20 30 40]
b[mask2] = [1 4 5]


## 5. np.where 条件选择

In [18]:
a = np.array([1, 2, 3, 4, 5])

# np.where(条件, 满足时的值, 不满足时的值)
result = np.where(a > 3, a, 0)
print('np.where(a > 3, a, 0) =', result)  # [0 0 0 4 5]

# 只传条件时返回满足条件的索引
indices = np.where(a > 3)
print('np.where(a > 3) =', indices)        # (array([3, 4]),)

# 二维示例
b = np.array([[10, 20], [30, 40]])
print('np.where(b > 25, b, -1) =')
print(np.where(b > 25, b, -1))  # 满足条件保留原值，否则填 -1

np.where(a > 3, a, 0) = [0 0 0 4 5]
np.where(a > 3) = (array([3, 4], dtype=int64),)
np.where(b > 25, b, -1) =
[[-1 -1]
 [30 40]]


## 6. 切片赋值与广播

In [19]:
a = np.zeros((3, 4), dtype=int)
print('初始 a =')
print(a)

# 整行赋值
a[0, :] = 1
print('a[0, :] = 1 后:')
print(a)

# 整列赋值
a[:, -1] = 9
print('a[:, -1] = 9 后:')
print(a)

# 布尔索引赋值
a[a == 0] = -1
print('a[a == 0] = -1 后:')
print(a)

初始 a =
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
a[0, :] = 1 后:
[[1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]
a[:, -1] = 9 后:
[[1 1 1 9]
 [0 0 0 9]
 [0 0 0 9]]
a[a == 0] = -1 后:
[[ 1  1  1  9]
 [-1 -1 -1  9]
 [-1 -1 -1  9]]


## 7. 常见陷阱：切片 vs 拷贝

In [20]:
a = np.array([1, 2, 3, 4, 5])

# 切片是视图（view），共享内存
b = a[1:4]
b[0] = 99
print('视图修改后 a =', a)     # a[1] 也变了 → [1 99 3 4 5]

# copy() 会创建独立副本
a = np.array([1, 2, 3, 4, 5])
c = a[1:4].copy()
c[0] = 99
print('copy 修改后 a =', a)    # a 不受影响 → [1 2 3 4 5]
print('c =', c)               # c = [99 3 4]

视图修改后 a = [ 1 99  3  4  5]
copy 修改后 a = [1 2 3 4 5]
c = [99  3  4]
