# py14: NumPy 数组操作

本 notebook 演示数组形状修改、翻转、维度变换、连接、分割、添加与删除。

In [27]:
import numpy as np

## 1. 修改数组形状

In [28]:
a = np.arange(12)
print('a =', a)

# reshape：不改变数据，返回新形状的视图
b = a.reshape(3, 4)
print('reshape(3,4) =')
print(b)

c = a.reshape(4, 3)
print('reshape(4,3) =')
print(c)

# -1 让 NumPy 自动推算该维度大小
d = a.reshape(2, -1)  # 等价于 reshape(2, 6)
print('reshape(2,-1) =')
print(d)

e = a.reshape(-1, 3)  # 等价于 reshape(4, 3)
print('reshape(-1,3) =')
print(e)

a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape(3,4) =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape(4,3) =
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
reshape(2,-1) =
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
reshape(-1,3) =
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
# flatten：展平为一维（返回拷贝）
b = a.reshape(3, 4)
f = b.flatten()
print('flatten =', f)
f[0] = 999
print('修改 flatten 后 b 不变')
print(b)

# ravel：展平为一维（返回视图，修改会影响原数组）
r = b.ravel()
print('ravel =', r)
r[0] = 999
print('修改 ravel 后 b 也变了')
print(b)

# resize：直接修改原数组形状（数据不够则重复填充）
a.resize(2, 6)
print('resize(2,6) =')
print(a)

flatten = [ 0  1  2  3  4  5  6  7  8  9 10 11]
修改 flatten 后 b 不变
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ravel = [ 0  1  2  3  4  5  6  7  8  9 10 11]
修改 ravel 后 b 也变了
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
resize(2,6) =
[[999   1   2   3   4   5]
 [  6   7   8   9  10  11]]


## 2. 翻转数组

In [30]:
a = np.arange(12).reshape(3, 4)
print('a =')
print(a)

# flip：沿指定轴翻转
print('flip(a, 0) 沿行翻转 =')
print(np.flip(a, 0))  # 上下翻转

print('flip(a, 1) 沿列翻转 =')
print(np.flip(a, 1))  # 左右翻转

print('flip(a) 全部翻转 =')
print(np.flip(a))     # 上下 + 左右

# fliplr / flipud：专用函数
print('fliplr =')
print(np.fliplr(a))  # 等价于 flip(a, 1)
print('flipud =')
print(np.flipud(a))  # 等价于 flip(a, 0)

a =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flip(a, 0) 沿行翻转 =
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
flip(a, 1) 沿列翻转 =
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
flip(a) 全部翻转 =
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
fliplr =
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
flipud =
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [31]:
# 一维数组翻转
x = np.array([1, 2, 3, 4, 5])
print('flip(x) =', np.flip(x))    # [5 4 3 2 1]
print('x[::-1] =', x[::-1])       # 同上，切片语法

flip(x) = [5 4 3 2 1]
x[::-1] = [5 4 3 2 1]


## 3. 修改数组维度

In [32]:
a = np.arange(6)
print('a =', a, 'shape:', a.shape)

# expand_dims：增加一个维度
b = np.expand_dims(a, axis=0)
print('expand_dims(axis=0) shape:', b.shape)  # (1, 6)
print(b)

c = np.expand_dims(a, axis=1)
print('expand_dims(axis=1) shape:', c.shape)  # (6, 1)
print(c)

# squeeze：移除长度为 1 的维度
d = np.array([[[1, 2, 3]]])  # shape (1, 1, 3)
print('squeeze 前 shape:', d.shape)
e = d.squeeze()
print('squeeze 后 shape:', e.shape, '→', e)  # (3,)

a = [0 1 2 3 4 5] shape: (6,)
expand_dims(axis=0) shape: (1, 6)
[[0 1 2 3 4 5]]
expand_dims(axis=1) shape: (6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
squeeze 前 shape: (1, 1, 3)
squeeze 后 shape: (3,) → [1 2 3]


In [33]:
# newaxis：快捷增加维度
a = np.arange(6)
print('a[np.newaxis, :] shape:', a[np.newaxis, :].shape)  # (1, 6)
print('a[:, np.newaxis] shape:', a[:, np.newaxis].shape)  # (6, 1)

# atleast_2d / atleast_3d：保证最低维度
x = np.array([1, 2, 3])
print('atleast_2d shape:', np.atleast_2d(x).shape)  # (1, 3)
print('atleast_3d shape:', np.atleast_3d(x).shape)  # (1, 1, 3)

a[np.newaxis, :] shape: (1, 6)
a[:, np.newaxis] shape: (6, 1)
atleast_2d shape: (1, 3)
atleast_3d shape: (1, 3, 1)


## 4. 连接数组

In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('a =')
print(a)
print('b =')
print(b)

# concatenate：沿已有轴连接
print('concatenate axis=0 (上下拼) =')
print(np.concatenate((a, b), axis=0))

print('concatenate axis=1 (左右拼) =')
print(np.concatenate((a, b), axis=1))

# vstack / hstack：便捷函数
print('vstack =')
print(np.vstack((a, b)))  # 等价于 concatenate axis=0
print('hstack =')
print(np.hstack((a, b)))  # 等价于 concatenate axis=1

a =
[[1 2]
 [3 4]]
b =
[[5 6]
 [7 8]]
concatenate axis=0 (上下拼) =
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=1 (左右拼) =
[[1 2 5 6]
 [3 4 7 8]]
vstack =
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack =
[[1 2 5 6]
 [3 4 7 8]]


In [35]:
# stack：沿新轴堆叠（需要形状一致）
print('stack axis=0 =')
print(np.stack((a, b), axis=0))  # shape (2, 2, 2)

print('stack axis=2 =')
print(np.stack((a, b), axis=2))  # shape (2, 2, 2)

stack axis=0 =
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
stack axis=2 =
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


## 5. 分割数组

In [36]:
a = np.arange(12).reshape(3, 4)
print('a =')
print(a)

# hsplit：沿水平方向（列）分割
print('hsplit(a, 2) =')  # 分成 2 块
for arr in np.hsplit(a, 2):
    print(arr)

# vsplit：沿垂直方向（行）分割
print('vsplit(a, 3) =')  # 分成 3 块
for arr in np.vsplit(a, 3):
    print(arr)

a =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
hsplit(a, 2) =
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]
vsplit(a, 3) =
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]


In [37]:
# 按索引位置分割
x = np.arange(10)
print('x =', x)
print('split(x, [3,7]) =')  # 在索引 3 和 7 处分割
for arr in np.split(x, [3, 7]):
    print(arr)

# array_split：允许不等分
print('array_split(x, 3) =')
for arr in np.array_split(x, 3):
    print(arr)

x = [0 1 2 3 4 5 6 7 8 9]
split(x, [3,7]) =
[0 1 2]
[3 4 5 6]
[7 8 9]
array_split(x, 3) =
[0 1 2 3]
[4 5 6]
[7 8 9]


## 6. 数组元素的添加与删除

In [38]:
a = np.array([1, 2, 3, 4, 5])
print('a =', a)

# append：末尾添加元素（返回新数组）
b = np.append(a, [6, 7, 8])
print('append =', b)  # [1 2 3 4 5 6 7 8]
print('原 a 不变 =', a)

# insert：在指定位置插入
c = np.insert(a, 2, [10, 20])  # 在索引 2 处插入
print('insert(2, [10,20]) =', c)  # [ 1  2 10 20  3  4  5]

# delete：删除指定位置的元素
d = np.delete(a, [0, 3])  # 删除索引 0 和 3
print('delete([0,3]) =', d)  # [2 3 5]

a = [1 2 3 4 5]
append = [1 2 3 4 5 6 7 8]
原 a 不变 = [1 2 3 4 5]
insert(2, [10,20]) = [ 1  2 10 20  3  4  5]
delete([0,3]) = [2 3 5]


In [39]:
# 二维数组的添加与删除
a = np.array([[1, 2], [3, 4]])
print('a =')
print(a)

# 沿 axis=0 添加行
b = np.append(a, [[5, 6]], axis=0)
print('append 行 =')
print(b)

# 沿 axis=1 添加列
c = np.append(a, [[7], [8]], axis=1)
print('append 列 =')
print(c)

# 删除行
d = np.delete(a, 0, axis=0)  # 删除第 0 行
print('delete 行 =')
print(d)

# 删除列
e = np.delete(a, 1, axis=1)  # 删除第 1 列
print('delete 列 =')
print(e)

a =
[[1 2]
 [3 4]]
append 行 =
[[1 2]
 [3 4]
 [5 6]]
append 列 =
[[1 2 7]
 [3 4 8]]
delete 行 =
[[3 4]]
delete 列 =
[[1]
 [3]]


## 7. 位运算

In [40]:
a = np.array([5, 3, 7])   # 二进制: 101, 011, 111
b = np.array([3, 6, 1])   # 二进制: 011, 110, 001
print('a =', a)
print('b =', b)

# bitwise_and：按位与（两位都为1才为1）
print('bitwise_and =', np.bitwise_and(a, b))  # [1, 2, 1]
print('  5 & 3 =', bin(5 & 3))   # 101 & 011 = 001

# bitwise_or：按位或（有一位为1就为1）
print('bitwise_or  =', np.bitwise_or(a, b))   # [7, 7, 7]
print('  5 | 3 =', bin(5 | 3))   # 101 | 011 = 111

# bitwise_xor：按位异或（两位不同为1）
print('bitwise_xor =', np.bitwise_xor(a, b))  # [6, 5, 6]
print('  5 ^ 3 =', bin(5 ^ 3))   # 101 ^ 011 = 110

a = [5 3 7]
b = [3 6 1]
bitwise_and = [1 2 1]
  5 & 3 = 0b1
bitwise_or  = [7 7 7]
  5 | 3 = 0b111
bitwise_xor = [6 5 6]
  5 ^ 3 = 0b110


In [41]:
# invert：按位取反（0变1，1变0）
print('a =', a)               # [5, 3, 7]
print('invert(a) =', np.invert(a))  # [-6, -4, -8]
print('  ~5 =', bin(~5))      # ~101 = ...11111010（补码）

# left_shift：左移（乘以 2^n）
print('left_shift(5, 1) =', np.left_shift(5, 1))   # 5 << 1 = 10
print('left_shift(3, 2) =', np.left_shift(3, 2))   # 3 << 2 = 12
print('  5 << 1 =', bin(5 << 1))  # 101 << 1 = 1010

# right_shift：右移（整除 2^n）
print('right_shift(10, 1) =', np.right_shift(10, 1))  # 10 >> 1 = 5
print('right_shift(12, 2) =', np.right_shift(12, 2))  # 12 >> 2 = 3
print('  10 >> 1 =', bin(10 >> 1))  # 1010 >> 1 = 101

a = [5 3 7]
invert(a) = [-6 -4 -8]
  ~5 = -0b110
left_shift(5, 1) = 10
left_shift(3, 2) = 12
  5 << 1 = 0b1010
right_shift(10, 1) = 5
right_shift(12, 2) = 3
  10 >> 1 = 0b101


In [42]:
# ---- 实际应用：用位运算做判断 ----
flags = np.array([0b1010, 0b1100, 0b0111, 0b1111])  # 4个标志位
mask = 0b0100  # 检查第2位是否为1

print('flags (二进制):', [bin(f) for f in flags])
print('mask (二进制):', bin(mask))
print('检查第2位:', np.bitwise_and(flags, mask) != 0)  # [False True False True]

# 用位运算打包/解包多个布尔标志
x, y, z = True, False, True
packed = (x << 2) | (y << 1) | z   # 打包为一个整数
print('打包:', packed, '=', bin(packed))  # 5 = 101

unpack_x = (packed >> 2) & 1  # 解包第2位
unpack_y = (packed >> 1) & 1  # 解包第1位
unpack_z = packed & 1         # 解包第0位
print('解包:', unpack_x, unpack_y, unpack_z)

flags (二进制): ['0b1010', '0b1100', '0b111', '0b1111']
mask (二进制): 0b100
检查第2位: [False  True  True  True]
打包: 5 = 0b101
解包: 1 0 1
