# py16: NumPy 数学、算术、统计与排序函数

本 notebook 演示 NumPy 常用数学函数、算术运算、统计函数、排序与条件筛选。

In [1]:
import numpy as np

## 1. 数学函数

In [2]:
a = np.array([0, 30, 45, 60, 90])

# 三角函数（输入为弧度）
print('sin =', np.sin(a * np.pi / 180))
print('cos =', np.cos(a * np.pi / 180))
print('tan =', np.tan(a * np.pi / 180))

# 反三角函数（返回弧度）
print('arcsin(0.5) =', np.arcsin(0.5))           # π/6
print('arcsin(0.5) 转角度 =', np.degrees(np.arcsin(0.5)))  # 30°

sin = [0.         0.5        0.70710678 0.8660254  1.        ]
cos = [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan = [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
arcsin(0.5) = 0.5235987755982989
arcsin(0.5) 转角度 = 30.000000000000004


In [3]:
# ---- 角度转换 ----
print('degrees(π) =', np.degrees(np.pi))      # 180.0
print('radians(180) =', np.radians(180))      # π

# ---- 幂与开方 ----
a = np.array([1, 4, 9, 16, 25])
print('sqrt =', np.sqrt(a))       # [1. 2. 3. 4. 5.]
print('square =', np.square(a))   # [ 1 16 81 256 625]
print('power(2,3) =', np.power(2, 3))  # 8

# ---- 指数与对数 ----
print('exp(1) =', np.exp(1))       # e ≈ 2.718
print('log(e) =', np.log(np.e))    # 1.0
print('log10(100) =', np.log10(100))  # 2.0
print('log2(8) =', np.log2(8))     # 3.0

degrees(π) = 180.0
radians(180) = 3.141592653589793
sqrt = [1. 2. 3. 4. 5.]
square = [  1  16  81 256 625]
power(2,3) = 8
exp(1) = 2.718281828459045
log(e) = 1.0
log10(100) = 2.0
log2(8) = 3.0


In [4]:
# ---- 取整函数 ----
a = np.array([1.2, 2.5, 3.7, -1.3, -2.8])
print('a =', a)
print('ceil  =', np.ceil(a))    # 向上取整 [ 2.  3.  4. -1. -2.]
print('floor =', np.floor(a))   # 向下取整 [ 1.  2.  3. -2. -3.]
print('round =', np.round(a))   # 四舍五入 [ 1.  2.  4. -1. -3.]
print('trunc =', np.trunc(a))   # 截断小数 [ 1.  2.  3. -1. -2.]
print('rint  =', np.rint(a))    # 四舍五入到最近整数 [ 1.  2.  4. -1. -3.]

a = [ 1.2  2.5  3.7 -1.3 -2.8]
ceil  = [ 2.  3.  4. -1. -2.]
floor = [ 1.  2.  3. -2. -3.]
round = [ 1.  2.  4. -1. -3.]
trunc = [ 1.  2.  3. -1. -2.]
rint  = [ 1.  2.  4. -1. -3.]


In [5]:
# ---- 绝对值与符号 ----
a = np.array([-3, -1, 0, 2, 5])
print('abs =', np.abs(a))         # [3 1 0 2 5]
print('sign =', np.sign(a))       # [-1 -1  0  1  1]

# ---- 最大公约数 ----
print('gcd(12, 8) =', np.gcd(12, 8))  # 4
print('lcm(12, 8) =', np.lcm(12, 8))  # 24

abs = [3 1 0 2 5]
sign = [-1 -1  0  1  1]
gcd(12, 8) = 4
lcm(12, 8) = 24


## 2. 算术函数

In [6]:
a = np.array([10, 20, 30])
b = np.array([3, 4, 5])

# 基本算术（逐元素）
print('加 =', np.add(a, b))        # [13 24 35]
print('减 =', np.subtract(a, b))   # [ 7 16 25]
print('乘 =', np.multiply(a, b))   # [30 80 150]
print('除 =', np.divide(a, b))     # [3.33 5. 6.]
print('整除 =', np.floor_divide(a, b))  # [3 5 6]
print('取模 =', np.mod(a, b))      # [1 0 0]
print('幂 =', np.power(b, 2))      # [ 9 16 25]

# Python 运算符也能用
print('a + b =', a + b)
print('a ** 2 =', a ** 2)

加 = [13 24 35]
减 = [ 7 16 25]
乘 = [ 30  80 150]
除 = [3.33333333 5.         6.        ]
整除 = [3 5 6]
取模 = [1 0 0]
幂 = [ 9 16 25]
a + b = [13 24 35]
a ** 2 = [100 400 900]


In [7]:
# ---- 倒数与负数 ----
a = np.array([1, 2, 4, 5])
print('reciprocal =', np.reciprocal(a))   # [1.  0.5 0.25 0.2]
print('negative =', np.negative(a))       # [-1 -2 -4 -5]

# ---- clip：截断到指定范围 ----
a = np.array([1, 5, 10, 15, 20])
print('clip(5,15) =', np.clip(a, 5, 15))  # [ 5  5 10 15 15]

reciprocal = [1 0 0 0]
negative = [-1 -2 -4 -5]
clip(5,15) = [ 5  5 10 15 15]


In [8]:
# ---- np.divmod：同时返回商和余数 ----
a = np.array([10, 20, 30])
b = np.array([3, 7, 8])
q, r = np.divmod(a, b)
print('商 =', q)  # [3 2 3]
print('余 =', r)  # [1 6 6]

商 = [3 2 3]
余 = [1 6 6]


## 3. 统计函数

In [9]:
a = np.array([10, 20, 30, 40, 50])
print('a =', a)

print('mean =', np.mean(a))      # 30.0 平均值
print('median =', np.median(a))  # 30.0 中位数
print('std =', np.std(a))        # 标准差
print('var =', np.var(a))        # 方差
print('sum =', np.sum(a))        # 150
print('cumsum =', np.cumsum(a))  # 累计和 [10 30 60 100 150]
print('prod =', np.prod(a))      # 12000000 积
print('cumprod =', np.cumprod(a))  # 累计积

a = [10 20 30 40 50]
mean = 30.0
median = 30.0
std = 14.142135623730951
var = 200.0
sum = 150
cumsum = [ 10  30  60 100 150]
prod = 12000000
cumprod = [      10      200     6000   240000 12000000]


In [10]:
# ---- 最值与百分位数 ----
a = np.array([15, 25, 10, 40, 30])
print('amin =', np.amin(a))     # 10 最小值
print('amax =', np.amax(a))     # 40 最大值
print('ptp =', np.ptp(a))       # 30 极差 (max - min)
print('percentile 25 =', np.percentile(a, 25))  # 下四分位
print('percentile 75 =', np.percentile(a, 75))  # 上四分位
print('quantile 0.5 =', np.quantile(a, 0.5))    # 等价于 median

amin = 10
amax = 40
ptp = 30
percentile 25 = 15.0
percentile 75 = 30.0
quantile 0.5 = 25.0


In [11]:
# ---- 二维数组统计（指定 axis） ----
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print('a =')
print(a)

print('全局 mean =', np.mean(a))       # 3.5
print('axis=0 mean =', np.mean(a, axis=0))  # [2.5 3.5 4.5] 按列求均
print('axis=1 mean =', np.mean(a, axis=1))  # [2. 5.] 按行求均

print('axis=0 sum =', np.sum(a, axis=0))  # [5 7 9]
print('axis=1 sum =', np.sum(a, axis=1))  # [ 6 15]

a =
[[1 2 3]
 [4 5 6]]
全局 mean = 3.5
axis=0 mean = [2.5 3.5 4.5]
axis=1 mean = [2. 5.]
axis=0 sum = [5 7 9]
axis=1 sum = [ 6 15]


In [12]:
# ---- NaN 安全版本 ----
a = np.array([1, 2, np.nan, 4, 5])
print('nanmean =', np.nanmean(a))   # 3.0 忽略 NaN
print('nansum  =', np.nansum(a))    # 12.0
print('nanstd  =', np.nanstd(a))    # 标准差
print('nanmin  =', np.nanmin(a))    # 1.0
print('nanmax  =', np.nanmax(a))    # 5.0

nanmean = 3.0
nansum  = 12.0
nanstd  = 1.5811388300841898
nanmin  = 1.0
nanmax  = 5.0


In [ ]:
# ---- np.average：加权平均 ----
a = np.array([1, 2, 3, 4])
print('average 无权重 =', np.average(a))  # 等价于 mean → 2.5

# 指定权重
weights = np.array([4, 3, 2, 1])
print('average 加权 =', np.average(a, weights=weights))
# (1*4+2*3+3*2+4*1)/(4+3+2+1) = 20/10 = 2.0

# returned=True 同时返回权重总和
result, wsum = np.average(a, weights=weights, returned=True)
print('加权均值 =', result, '权重和 =', wsum)

# 二维数组加权平均
b = np.arange(6).reshape(3, 2)
print('b =')
print(b)
wt = np.array([3, 5])
print('axis=1 加权平均 =', np.average(b, axis=1, weights=wt))
# [0.625, 2.625, 4.625]

## 4. 排序函数

In [13]:
# ---- np.sort：返回排序后的新数组（不修改原数组） ----
a = np.array([30, 10, 50, 20, 40])
print('原数组 =', a)
print('sort =', np.sort(a))           # [10 20 30 40 50]
print('原数组不变 =', a)               # [30 10 50 20 40]

# 降序排序
print('sort 降序 =', np.sort(a)[::-1])  # [50 40 30 20 10]

# kind 参数：排序算法
print('sort kind=quicksort =', np.sort(a, kind='quicksort'))
print('sort kind=mergesort =', np.sort(a, kind='mergesort'))
print('sort kind=heapsort  =', np.sort(a, kind='heapsort'))

原数组 = [30 10 50 20 40]
sort = [10 20 30 40 50]
原数组不变 = [30 10 50 20 40]
sort 降序 = [50 40 30 20 10]
sort kind=quicksort = [10 20 30 40 50]
sort kind=mergesort = [10 20 30 40 50]
sort kind=heapsort  = [10 20 30 40 50]


In [14]:
# ---- ndarray.sort()：原地排序（修改原数组） ----
a = np.array([30, 10, 50, 20, 40])
print('排序前 =', a)
a.sort()
print('排序后 =', a)  # [10 20 30 40 50] 原数组已变

排序前 = [30 10 50 20 40]
排序后 = [10 20 30 40 50]


In [15]:
# ---- 二维数组排序 ----
a = np.array([[30, 10, 50],
              [40, 20, 60]])
print('axis=None 全局排序 =', np.sort(a, axis=None))
# [10 20 30 40 50 60]

print('axis=0 按列排序 =')
print(np.sort(a, axis=0))
# [[30 10 50]
#  [40 20 60]]  每列内部排序

print('axis=1 按行排序 =')
print(np.sort(a, axis=1))
# [[10 30 50]
#  [20 40 60]]  每行内部排序

axis=None 全局排序 = [10 20 30 40 50 60]
axis=0 按列排序 =
[[30 10 50]
 [40 20 60]]
axis=1 按行排序 =
[[10 30 50]
 [20 40 60]]


## 5. 条件筛选函数

In [16]:
a = np.array([30, 10, 50, 20, 40])

# ---- argmin / argmax：最值的索引 ----
print('argmin =', np.argmin(a))  # 1（a[1]=10 最小）
print('argmax =', np.argmax(a))  # 2（a[2]=50 最大）

# ---- argsort：排序后的索引 ----
print('argsort =', np.argsort(a))  # [1 3 0 4 2]
# 解读：a[1]=10 最小，a[3]=20 第二，a[0]=30 第三...

# 用 argsort 做间接排序
print('按 argsort 取值 =', a[np.argsort(a)])  # [10 20 30 40 50]

argmin = 1
argmax = 2
argsort = [1 3 0 4 2]
按 argsort 取值 = [10 20 30 40 50]


In [17]:
# ---- np.where：条件选择 ----
a = np.array([10, 20, 30, 40, 50])

# 条件赋值
result = np.where(a > 25, a, 0)
print('where(a>25, a, 0) =', result)  # [ 0  0 30 40 50]

# 只传条件：返回满足条件的索引
print('where(a>25) 索引 =', np.where(a > 25))  # (array([2, 3, 4]),)

# 嵌套条件
result = np.where(a > 40, 'high', 
                   np.where(a > 20, 'mid', 'low'))
print('嵌套 where =', result)  # ['low' 'low' 'mid' 'mid' 'high']

where(a>25, a, 0) = [ 0  0 30 40 50]
where(a>25) 索引 = (array([2, 3, 4], dtype=int64),)
嵌套 where = ['low' 'low' 'mid' 'mid' 'high']


In [18]:
# ---- np.nonzero：非零元素的索引 ----
a = np.array([0, 5, 0, 3, 0, 7])
print('nonzero =', np.nonzero(a))  # (array([1, 3, 5]),)
print('取非零值 =', a[np.nonzero(a)])  # [5 3 7]

# ---- np.unique：去重 ----
a = np.array([3, 1, 2, 3, 1, 4, 2])
print('unique =', np.unique(a))  # [1 2 3 4]
u, idx, counts = np.unique(a, return_index=True, return_counts=True)
print('unique 值 =', u)       # [1 2 3 4]
print('首次出现索引 =', idx)   # [1 2 0 6]
print('出现次数 =', counts)    # [2 2 2 1]

nonzero = (array([1, 3, 5], dtype=int64),)
取非零值 = [5 3 7]
unique = [1 2 3 4]
unique 值 = [1 2 3 4]
首次出现索引 = [1 2 0 5]
出现次数 = [2 2 2 1]


In [19]:
# ---- np.in1d / np.isin：判断元素是否在指定集合中 ----
a = np.array([10, 20, 30, 40, 50])
print('in1d(a>25) =', np.in1d(a, [30, 40]))  # [False False True True False]
print('isin(a>25) =', np.isin(a, [30, 40]))   # 同上

# ---- np.select：多条件分支选择 ----
a = np.array([10, 20, 30, 40, 50])
conds = [a < 20, (a >= 20) & (a < 40), a >= 40]
choices = ['low', 'mid', 'high']
print('select =', np.select(conds, choices))  # ['low' 'mid' 'mid' 'high' 'high']

in1d(a>25) = [False False  True  True False]
isin(a>25) = [False False  True  True False]
select = ['low' 'mid' 'mid' 'high' 'high']


## 6. 矩阵运算

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# 逐元素乘法
print('a * b =')
print(a * b)

# 矩阵乘法
print('dot =')
print(np.dot(a, b))
# [[19 22]
#  [43 50]]

print('matmul (@) =')
print(a @ b)  # 等价于 np.dot(a, b)

a * b =
[[ 5 12]
 [21 32]]
dot =
[[19 22]
 [43 50]]
matmul (@) =
[[19 22]
 [43 50]]


In [21]:
# ---- 线性代数常用 ----
a = np.array([[1, 2], [3, 4]])

print('trace（对角线和） =', np.trace(a))  # 1+4=5
print('det（行列式） =', np.linalg.det(a))  # 1*4-2*3 = -2
print('inv（逆矩阵） =')
print(np.linalg.inv(a))
print('eig（特征值/特征向量） =')
vals, vecs = np.linalg.eig(a)
print('特征值 =', vals)
print('特征向量 =')
print(vecs)

trace（对角线和） = 5
det（行列式） = -2.0000000000000004
inv（逆矩阵） =
[[-2.   1. ]
 [ 1.5 -0.5]]
eig（特征值/特征向量） =
特征值 = [-0.37228132  5.37228132]
特征向量 =
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
